//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bollard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BollardVioEventEntities : DbContext
    {
        public BollardVioEventEntities()
            : base("name=BollardVioEventEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOLLARDIMAGEOCCUPANCY> BOLLARDIMAGEOCCUPANCies { get; set; }
        public virtual DbSet<BollardImage> BollardImages { get; set; }
        public virtual DbSet<enf_permits> enf_permits { get; set; }
        public virtual DbSet<EnfVendorPayStation> EnfVendorPayStations { get; set; }
        public virtual DbSet<EnfVendorStall> EnfVendorStalls { get; set; }
        public virtual DbSet<EnfVendorTransaction> EnfVendorTransactions { get; set; }
        public virtual DbSet<HousingMaster> HousingMasters { get; set; }
        public virtual DbSet<MeterMap> MeterMaps { get; set; }
        public virtual DbSet<Meter> Meters { get; set; }
        public virtual DbSet<ParkingSpaceOccupancy> ParkingSpaceOccupancies { get; set; }
        public virtual DbSet<ParkingSpaceOccupancyAudit> ParkingSpaceOccupancyAudits { get; set; }
        public virtual DbSet<EnfBollardLPREvent> EnfBollardLPREvents { get; set; }
        public virtual DbSet<EnfBollardVioEvent> EnfBollardVioEvents { get; set; }
        public virtual DbSet<enfbollardvioeventTest> enfbollardvioeventTests { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
    }
}
