//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bollard
{
    using System;
    using System.Collections.Generic;
    
    public partial class BollardImage
    {
        public long Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public long BollardImageOccupancyId { get; set; }
        public byte[] BollardImage1 { get; set; }
        public string BollardImageBase64 { get; set; }
    
        public virtual BOLLARDIMAGEOCCUPANCY BOLLARDIMAGEOCCUPANCY { get; set; }
    }
}
