//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bollard
{
    using System;
    using System.Collections.Generic;
    
    public partial class enf_permits
    {
        public long Id { get; set; }
        public int ENFCustomerId { get; set; }
        public System.DateTime ENFCreatedDateTime { get; set; }
        public string ENFPlateNo { get; set; }
        public string ENFState { get; set; }
        public string ENFSource { get; set; }
        public string ENFType { get; set; }
        public Nullable<System.DateTime> EnfFileDateTime { get; set; }
        public string ENFFileSource { get; set; }
        public Nullable<System.DateTime> ENFEndDate { get; set; }
        public string ENFPermitID { get; set; }
        public string ZoneName { get; set; }
        public string ENFPermitNo { get; set; }
        public string ZoneID { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<System.DateTime> TxnDateTime { get; set; }
        public string TxnReferenceId { get; set; }
        public string DIST_CODE { get; set; }
        public string DISTRICT { get; set; }
        public string A1 { get; set; }
    }
}
