//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bollard
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnfBollardLPREvent
    {
        public long Id { get; set; }
        public Nullable<long> EnfCustomerId { get; set; }
        public Nullable<long> EnfVendorId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<long> EnfPayStationId { get; set; }
        public string Name { get; set; }
        public Nullable<long> EnfZoneId { get; set; }
        public string EnfZoneName { get; set; }
        public string Block { get; set; }
        public string Street { get; set; }
        public Nullable<System.DateTime> ViolationDatetime { get; set; }
        public Nullable<System.DateTime> LPEntryDatetime { get; set; }
        public Nullable<System.DateTime> LPExitDatetime { get; set; }
        public string PlateNumber { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> UpDatedDate { get; set; }
        public string PlateImage { get; set; }
        public string ContextImage { get; set; }
        public string OverviewImage { get; set; }
        public Nullable<long> BollardEntryRefId { get; set; }
        public string HitId { get; set; }
        public Nullable<int> HitType { get; set; }
        public string AlertStatus { get; set; }
        public string State { get; set; }
        public string BollardUserAction { get; set; }
        public string RejectReason { get; set; }
        public string HIT_ACCEPT_REASONS { get; set; }
        public Nullable<bool> IsException { get; set; }
        public Nullable<bool> IsViolated { get; set; }
        public string Note { get; set; }
        public string UserAction { get; set; }
        public string NewStatus { get; set; }
        public string Citation_Number { get; set; }
        public string UserName { get; set; }
        public string UserId { get; set; }
        public Nullable<int> SpaceType { get; set; }
        public string OldPlateNumber { get; set; }
        public Nullable<System.DateTime> PlateModifiedOn { get; set; }
        public string PlateModifiedBy { get; set; }
        public string Source { get; set; }
        public Nullable<long> PlateImageId { get; set; }
        public Nullable<bool> IsAbandoned { get; set; }
        public Nullable<System.DateTime> AbandonedDateTime { get; set; }
    }
}
