//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bollard
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnfVendorStall
    {
        public int EnfVendorStallId { get; set; }
        public long EnfCustomerId { get; set; }
        public long EnfVendorId { get; set; }
        public int StallNumber { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public Nullable<System.DateTime> PurchasedOn { get; set; }
        public Nullable<byte> EnfVSStatus { get; set; }
        public Nullable<int> SettingId { get; set; }
        public Nullable<long> CSParkingSpaceId { get; set; }
        public string SteetName { get; set; }
        public string Location { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> PayStationId { get; set; }
        public string Block { get; set; }
        public string Direction { get; set; }
        public string StreetType { get; set; }
        public string CrossStreet1 { get; set; }
        public string CrossStreet2 { get; set; }
        public string MeterID { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public Nullable<int> SpaceType { get; set; }
    
        public virtual EnfVendorPayStation EnfVendorPayStation { get; set; }
    }
}
