//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bollard
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnfVendorTransaction
    {
        public long Id { get; set; }
        public Nullable<long> EnfCustomerId { get; set; }
        public Nullable<long> EnfVendorId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> PayStationId { get; set; }
        public Nullable<int> SettingsId { get; set; }
        public Nullable<long> TicketNumber { get; set; }
        public Nullable<long> StallId { get; set; }
        public Nullable<System.DateTime> PurchasedDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public string CardType { get; set; }
        public string CardNumber { get; set; }
        public Nullable<int> CardPocessingRetries { get; set; }
        public string CardProcessingTxnId { get; set; }
        public string PaidCitationNumber { get; set; }
        public string ExcessAmountPaid { get; set; }
        public Nullable<decimal> RefundTicketAmount { get; set; }
        public Nullable<decimal> RefundChangeIssued { get; set; }
        public Nullable<decimal> ChargedAmount { get; set; }
        public Nullable<decimal> TotalCashAmount { get; set; }
        public Nullable<decimal> TotalCardAmount { get; set; }
        public Nullable<int> RateId { get; set; }
        public string RateName { get; set; }
        public string PlateNumber { get; set; }
        public Nullable<long> PayByCellVendorId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string SerialNumber { get; set; }
        public string paystationType { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string cardProcessingAuthorizationNumber { get; set; }
        public Nullable<System.DateTime> cardProcessingDate { get; set; }
        public string cardProcessingStatus { get; set; }
        public string cardProcessingReferenceNumber { get; set; }
        public string cardProcessingMerchantAccount { get; set; }
        public string couponNumber { get; set; }
        public Nullable<int> couponDiscountPercent { get; set; }
        public Nullable<decimal> couponDiscountDollar { get; set; }
        public Nullable<decimal> RateValue { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public string TerminalID { get; set; }
        public string ArticleName { get; set; }
        public string ParkingSpaceID { get; set; }
        public string ParkingSpaceTerminalGroup { get; set; }
        public string RegistrationNumberState { get; set; }
        public string CARCODE { get; set; }
        public Nullable<int> CARCODEID { get; set; }
        public string CarPlateNumber { get; set; }
        public string MotoristAccountNumber { get; set; }
    
        public virtual EnfVendorPayStation EnfVendorPayStation { get; set; }
    }
}
