//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bollard
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnfVendorPayStation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnfVendorPayStation()
        {
            this.EnfVendorStalls = new HashSet<EnfVendorStall>();
            this.EnfVendorTransactions = new HashSet<EnfVendorTransaction>();
        }
    
        public int EnfVPSId { get; set; }
        public long EnfCustomerId { get; set; }
        public long EnfVendorId { get; set; }
        public string SerialNumber { get; set; }
        public string Name { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> CSMeterId { get; set; }
        public Nullable<int> CSCustomerId { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public string Block { get; set; }
        public string Direction { get; set; }
        public string StreetType { get; set; }
        public string CrossStreet1 { get; set; }
        public string CrossStreet2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnfVendorStall> EnfVendorStalls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnfVendorTransaction> EnfVendorTransactions { get; set; }
    }
}
