//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bollard
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterMap
    {
        public int Customerid { get; set; }
        public int Areaid { get; set; }
        public int MeterId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public int HousingId { get; set; }
        public Nullable<int> MechId { get; set; }
        public Nullable<int> AreaId2 { get; set; }
        public Nullable<int> CollRouteId { get; set; }
        public Nullable<int> EnfRouteId { get; set; }
        public Nullable<int> MaintRouteId { get; set; }
        public int id { get; set; }
        public Nullable<int> CustomGroup1 { get; set; }
        public Nullable<int> CustomGroup2 { get; set; }
        public Nullable<int> CustomGroup3 { get; set; }
        public Nullable<int> SubAreaID { get; set; }
        public Nullable<int> CashBoxID { get; set; }
        public Nullable<long> CollectionRunId { get; set; }
        public Nullable<int> DataKeyId { get; set; }
        public Nullable<int> sensorid { get; set; }
        public Nullable<int> gatewayid { get; set; }
        public Nullable<int> CSParkId { get; set; }
        public string CustomField { get; set; }
    
        public virtual HousingMaster HousingMaster { get; set; }
        public virtual Meter Meter { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
