//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bollard
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSpaceOccupancy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParkingSpaceOccupancy()
        {
            this.ParkingSpaceOccupancyAudits = new HashSet<ParkingSpaceOccupancyAudit>();
        }
    
        public long ParkingSpaceOccupancyId { get; set; }
        public long ParkingSpaceId { get; set; }
        public int LastStatus { get; set; }
        public System.DateTime LastUpdatedTS { get; set; }
        public Nullable<int> GCustomerid { get; set; }
        public Nullable<int> GAreaId { get; set; }
        public Nullable<int> GMeterId { get; set; }
        public byte[] DiagnosticData { get; set; }
        public Nullable<int> LQI { get; set; }
        public Nullable<int> GwayCustomerId { get; set; }
        public Nullable<int> GwayAreaId { get; set; }
        public Nullable<int> GwayMeterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkingSpaceOccupancyAudit> ParkingSpaceOccupancyAudits { get; set; }
    }
}
